### ISSUE TITLE
CreateError when attempting to create a table

### ISSUE THREAD

**Issue by lucrussell** [bryanyang0528/ksql-python#33]
I'm getting an error when trying to create a table. This is the code:
```
from ksql import KSQLAPI
client = KSQLAPI('http://localhost:8088')
client.create_table(table_name='mytable',
                    columns_type=['viewtime bigint', 'userid varchar', 'pageid varchar'],
                    topic='mytopic',
                    value_format='JSON')
```
and the error:
```
Traceback (most recent call last):
  File "/home/lrussell/Dev/ksql-plotly-dash/basic.py", line 6, in <module>
    value_format='JSON')
  File "/home/lrussell/.virtualenvs/ksql-plotly-dash/lib/python3.6/site-packages/ksql/client.py", line 50, in create_table
    value_format = value_format)
  File "/home/lrussell/.virtualenvs/ksql-plotly-dash/lib/python3.6/site-packages/ksql/api.py", line 142, in create_table
    value_format=value_format)
  File "/home/lrussell/.virtualenvs/ksql-plotly-dash/lib/python3.6/site-packages/ksql/api.py", line 164, in _create
    return self._parse_ksql_res(r, CreateError)
  File "/home/lrussell/.virtualenvs/ksql-plotly-dash/lib/python3.6/site-packages/ksql/api.py", line 40, in _parse_ksql_res
    raise CreateError(r)
ksql.errors.CreateError: Cannot define a TABLE without providing the KEY column name in the WITH clause.
```
I think the error might be related to [this line](https://github.com/bryanyang0528/ksql-python/blob/b36d0792284e5ddd3444a33f8fe8969680322013/ksql/builder.py#L74). Maybe it needs an extra value in the `WITH` clause for the key? The key isn't listed as a required property for creating tables according to the KSQL documentation, but possibly something has changed recently.

**Comment by bryanyang0528** [comment]
@lucrussell  Which version of KSQL server do you use?

**Comment by lucrussell** [comment]
I'm using `4.1.0`.

**Comment by davit555** [comment]
Guys any updates on this

**Comment by bryanyang0528** [comment]
It's seem fine now
```
>>> client = KSQLAPI('http://ksql-server:8088')
>>> client.create_table(table_name='mytable',
...                     columns_type=['viewtime bigint', 'userid varchar', 'pageid varchar'],
...                     topic='mytopic',
...                     value_format='JSON', key='viewtime')
True
>>> client.ksql('show tables')
[{'tables': {'statementText': 'show tables;', 'tables': [{'name': 'MYTABLE', 'topic': 'mytopic', 'format': 'JSON', 'isWindowed': False}]}}]
>>>
```

**Comment by davit555** [comment]
thanks for the fix ;)

**Comment by lucrussell** [comment]
thanks! :+1:
