### ISSUE TITLE
pip package broken

### ISSUE THREAD

**Issue by chokosabe** [bryanyang0528/ksql-python#51]
MacOSX 10.14.2
Python3 installed using brew

running pip install ksql gives this error:

Collecting ksql
  Downloading https://files.pythonhosted.org/packages/98/9f/1187d5bf9ab6e68c23fde44f93df2e1aae94083e1c6608a299aa1c6a99f5/ksql-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jp/s96xr96s7k3g94fsvpbdh9cr0000gn/T/pip-install-tkknoxhn/ksql/setup.py", line 52, in <module>
        install_requires=get_install_requirements("requirements.txt"),
      File "/private/var/folders/jp/s96xr96s7k3g94fsvpbdh9cr0000gn/T/pip-install-tkknoxhn/ksql/setup.py", line 27, in get_install_requirements
        content = open(os.path.join(os.path.dirname(__file__), path)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/jp/s96xr96s7k3g94fsvpbdh9cr0000gn/T/pip-install-tkknoxhn/ksql/requirements.txt'

I think the setup.py file is missing

**Comment by bryanyang0528** [comment]
@chokosabe  Thank you for reporting this bug, I'll test it again and updated ASAP

**Comment by crocus** [comment]
**Still get an error:**
/opt/anaconda3/bin/python -m pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org  --upgrade ksql
Collecting ksql
  Downloading https://files.pythonhosted.org/packages/98/9f/1187d5bf9ab6e68c23fde44f93df2e1aae94083e1c6608a299aa1c6a99f5/ksql-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cwddsvt7/ksql/setup.py", line 52, in <module>
        install_requires=get_install_requirements("requirements.txt"),
      File "/tmp/pip-install-cwddsvt7/ksql/setup.py", line 27, in get_install_requirements
        content = open(os.path.join(os.path.dirname(__file__), path)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-cwddsvt7/ksql/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cwddsvt7/ksql/
