### ISSUE TITLE
IndexError after inserting

### ISSUE THREAD

**Issue by agmo1993** [bryanyang0528/ksql-python#80]
i'm receiving the following error after inserting into a stream using 

```python
client.ksql("INSERT INTO riderLocations (profileId, latitude, longitude) VALUES ('4ab5cbad', 37.3952, -122.0813);")`
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ksql/client.py", line 42, in ksql
    return self.sa.ksql(ksql_string, stream_properties=stream_properties)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ksql/api.py", line 64, in ksql
    self._raise_for_status(r, response)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ksql/api.py", line 54, in _raise_for_status
    if r_json[0]["@type"] == "currentStatus" and r_json[0]["commandStatus"]["status"] == "ERROR":
IndexError: list index out of range

Although the insert is successful and I can view it on a select query, any ideas about what's causing it to throw an error?

**Comment by bryanyang0528** [comment]
@agmo1993 Thank you for reporting issue. I will check the API response.

**Comment by romainr** [comment]
Indeed, I see the same.

Seems like we get `[]`

**Comment by romainr** [comment]
Not sure if it is the best way to fix it but it avoids it

https://github.com/bryanyang0528/ksql-python/pull/88

**Comment by javiersvg** [comment]
I have the same issue.
In my case the insert call is returning an empty array even though the insertion is ssuccessfull:
```
curl -X "POST" "http://localhost:8088/ksql" -H "Content-Type: application/json; charset=utf-8" -d @ksql-request.json -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8088 (#0)
> POST /ksql HTTP/1.1
> Host: localhost:8088
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json; charset=utf-8
> Content-Length: 375
>
* upload completely sent off: 375 out of 375 bytes
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 2
<
* Connection #0 to host localhost left intact
[]
```

**Comment by bryanyang0528** [comment]
@romainr Thank you for fixing it. Good contribution!

**Comment by bryanyang0528** [comment]
@agmo1993  Please try if this fixes this issue. Thank you.

**Comment by javiersvg** [comment]
I had the same issue and this solved it. When do you think will this be released?

**Comment by ozair-junior** [comment]
While we are waiting, I make this _local correction_ :wink: :

```
class KsqlApiCustom(KSQLAPI):
    def __init__(self, url, max_retries=3, check_version=True, **kwargs):
        super().__init__(url, max_retries=max_retries,
                         check_version=check_version, **kwargs)
        self.sa._raise_for_status = self._raise_for_status

    @staticmethod
    def _raise_for_status(r, response):
        r_json = json.loads(response)
        if r.getcode() != 200:
            # seems to be the new API behavior
            if r_json.get("@type") == "statement_error" or r_json.get("@type") == "generic_error":
                error_message = r_json["message"]
                error_code = r_json["error_code"]
                stackTrace = r_json["stack_trace"]
                raise KSQLError(error_message, error_code, stackTrace)
            else:
                raise KSQLError("Unknown Error: {}".format(r.content))
        else:
            # seems to be the old API behavior, so some errors have status 200, bug??
            if r_json and r_json[0]["@type"] == "currentStatus" and r_json[0]["commandStatus"]["status"] == "ERROR":
                error_message = r_json[0]["commandStatus"]["message"]
                error_code = None
                stackTrace = None
                raise KSQLError(error_message, error_code, stackTrace)
            return True

**Comment by KenCox94** [comment]
should be seeing a new release relatively soon. @bryanyang0528 is hard at work on updating the project. thanks for your patience.

**Comment by rgbarry** [comment]
Thank you @ozair-junior !!!
